// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7ZxZqlH4svgtyMOBakSUWTo1urptU0c',
    appId: '1:663276517249:web:2639421ae14f8652b51a80',
    messagingSenderId: '663276517249',
    projectId: 'citex-website',
    authDomain: 'citex-website.firebaseapp.com',
    storageBucket: 'citex-website.appspot.com',
    measurementId: 'G-4NN0QQBKR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihqYRAluWR9xufenBx5-wVz64BWNx374',
    appId: '1:663276517249:android:5b67750f748cc71fb51a80',
    messagingSenderId: '663276517249',
    projectId: 'citex-website',
    storageBucket: 'citex-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIWgbdm45_HofuQyWEzpiqTPYqUrMdCSY',
    appId: '1:663276517249:ios:69a94dbdc15b0b64b51a80',
    messagingSenderId: '663276517249',
    projectId: 'citex-website',
    storageBucket: 'citex-website.appspot.com',
    iosBundleId: 'com.example.expoDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIWgbdm45_HofuQyWEzpiqTPYqUrMdCSY',
    appId: '1:663276517249:ios:4fc09873f65c795cb51a80',
    messagingSenderId: '663276517249',
    projectId: 'citex-website',
    storageBucket: 'citex-website.appspot.com',
    iosBundleId: 'com.example.expoDemo.RunnerTests',
  );
}
